
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subesdb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - springapimysql-net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net


  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    networks:
      - springapimysql-net
    ports:
      - "5173:5173"

networks:
  springapimysql-net:
    driver: bridge

volumes:
  mysql-data:
