-- Insertar usuarios
INSERT INTO users (username, password, email, bio, profilePic, headerPic, country) VALUES
('Alex Suarez', 'contraseña1', 'usuario1@example.com', '¡Hola! Soy Alex Suarez, un apasionado Diseñador con un amor profundo por la creatividad y la tecnología. Me considero un eterno soñador que se dedica a convertir ideas innovadoras en experiencias digitales asombrosas. Mi enfoque se basa en fusionar diseño y funcionalidad para crear soluciones impactantes y atractivas.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/ycdimolbpuauqkatktdr', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/hkdmcot1wtsoxpldknfy', 'España'),
('Marco Rossi', 'contraseña2', 'usuario2@example.com', 'Biografía del usuario 2.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/etdloictcibumnn5zsso', 'ruta/a/imagen4.jpg', 'México'),
('Javier Galiñanes', 'contraseña3', 'usuario3@example.com', 'Biografía del usuario 3.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/iwcu1x3lp9xh4yrnj5bt', 'ruta/a/imagen6.jpg', 'Argentina'),
('Teo Gallego', 'contraseña4', 'usuario4@example.com', 'Hola chavales soy Teo.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/jowj9hsqy0ji7bjilbuz', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/fbdxi8g5duz63egpv9c0', 'Francia'),
('Lola Bermudez', 'contraseña5', 'usuario5@example.com', 'Biografía del usuario 5.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/lrxuaopivyguobr8tdmn', 'ruta/a/imagen10.jpg', 'Chile'),
('Adriano Fric', 'contrachele', 'chele@mail.com', 'Soy chele chavales como estamos.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/qkrzgxntpcddfujeub0x', 'ruta/a/imagen16.jpg', 'Spain'),
('Manuel Casal', 'contramanu', 'manu@mail.com', 'Acabana Racing.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/yrfhrqvr5m7qltbbzjle', 'ruta/a/imagen16.jpg', 'Spain'),
('Gustavo Nieto', 'contragus', 'gus@mail.com', 'A mi no me da la lu yo soy la lu gusilu.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/y1zh9san8r1ns4vmyfk4', 'ruta/a/imagen16.jpg', 'Venezuela'),
('Carmen Faginas', 'contramela', 'mela@mail.com', 'Hola soy Mela!', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/fq2ghkimwjonhe0mtirt', 'ruta/a/imagen16.jpg', 'Spain'),
('Lucia Parra', 'contraina', 'ina@mail.com', 'Hola soy Lucia!', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/wg85di8piznmnfh0mqtt', 'ruta/a/imagen16.jpg', 'Spain'),
('Malena Fariña', 'contramalena', 'malena@mail.com', 'MaryMuffin para los amigos, la que pinta sudaderas en ByeMels', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/yortz5esfdudnl9daqmr', 'ruta/a/imagen16.jpg', 'Turquia'),
('Sergio Sanchez', 'contrasergios', 'sergios@mail.com', 'Corro porque vi la peli de Forrest Gump de pequeño y el corria y aun no pare de correr se nota que soy de la sierra chaval.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/onr6cc0atiglpn1arx5e', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/e56hoqvvj81hnwsokr2u', 'Navalcarnero'),
('Alejandro Brea', '123456', 'brea@mail.com', 'Jeje soy yo.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/jkicsldr5dzih432gfyw', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/lhztro6kubixafkjazap', 'Spain'),
('Anail Perez', 'contraanail', 'anail@mail.com', 'Hola soy Anail! Vivo en Vigo y soy muy bajita', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/qjwrmlft4r4vph2heiyp', 'ruta/a/imagen16.jpg', 'Vigo'),
('Marta Vilas', 'contramarta', 'marta@mail.com', 'Vivo en Santiago y juego al hockey mientras me saco una carrera!', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/g5qm3ugbme7fxsa7wbhr', 'ruta/a/imagen16.jpg', 'Santiago'),
('Lucas Dann', 'contralucas', 'lucas@mail.com', 'Hey all! Im Lucas, ecology is my pasion and i want to share some projects to protect our planet', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/t1mlb5ovirt50cbud72v', 'ruta/a/imagen16.jpg', 'Holanda');

-- Insertar publicaciones
-- Publicaciones para usuario1
INSERT INTO posts (title, technologies, subTitle, description, subTitle2, description2, media, user_id, category) VALUES
('Canary Islands paradise project', 'Adobe Photoshop - Adobe Ilustrator', 'Exploring Natures Canvas: Capturing the Essence of Canary Islands', 'In the heart of the Atlantic Ocean lies a hidden gem, the Canary Islands, a paradise of unparalleled beauty waiting to be explored through the lens of a camera. Our project, "Canary Islands Paradise," embarks on a photographic journey to showcase the captivating landscapes, diverse ecosystems, and vibrant culture of this enchanting archipelago. From the dramatic cliffs of Tenerife to the golden sands of Gran Canaria, our lenses capture the essence of this unique paradise. Through our images, we aim to transport viewers into a world where azure waters meet lush greenery, where ancient traditions blend seamlessly with modern life, and where every frame tells a story of the islands rich natural heritage.', 'Colors of Serenity: A Visual Ode to Canary Islands Paradise', 'In our photographic odyssey, Colors of Serenity, we delve into the chromatic wonders that define the Canary Islands unparalleled beauty. Each frame captures the interplay of hues that paint the skies during sunrise and sunset, the rich marine blues that surround the islands, and the vibrant flora that adorns the landscape. From the fiery reds of volcanic terrain to the soothing pastels of quaint coastal villages, our lenses unveil the poetic serenity of the Canary Islands. This project goes beyond mere visuals; it is an ode to the harmonious blend of colors that evoke a sense of peace and tranquility unique to this paradise. Through our photographs, we invite viewers to immerse themselves in the soothing palette of the Canary Islands and experience the serenity that nature so generously bestows upon this enchanting destination.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/muwpghrjwczznslolafu', 1, 'DESIGN');

-- Publicaciones para usuario2
INSERT INTO posts (title, technologies, subTitle, description, media, user_id, category) VALUES
('Accesible Ticket Website', 'Tecnologías de la publicación 1 para usuario2', 'Subtítulo de la publicación 1 para usuario2', 'Redesign an event ticketing website with a focus on accessibility and inclusivity. Prioritize user-friendly navigation, clear information presentation, and features that cater to individuals with diverse needs, ensuring a seamless experience for all users.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/cnaj3kkd8dhczjupsvaw', 2, 'DEVELOPMENT'),
('Eco-friendly Habit Tracker App', 'Tecnologías de la publicación 2 para usuario2', 'Subtítulo de la publicación 2 para usuario2', 'Mobile app that encourages users to adopt eco-friendly habits. The app could include features like personalized challenges, progress tracking, and social sharing to promote a sustainable lifestyle', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/mpelykw9q5lrak6zkark', 2, 'DEVELOPMENT');


-- Publicaciones para usuario3
INSERT INTO posts (title, technologies, subTitle, description, media, user_id, category) VALUES
('AI-Powered Personal Health Assistant', 'Tecnologías de la publicación 1 para usuario3', 'Subtítulo de la publicación 1 para usuario3', 'Health and wellness application that utilizes artificial intelligence to provide personalized health recommendations, track fitness goals, and offer real-time assistance for maintaining a healthy lifestyle', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/jb6tmuiakjaxfmchw127', 3, 'DESIGN'),
('Branding and Packaging for Sustainable Products', 'Tecnologías de la publicación 2 para usuario3', 'Subtítulo de la publicación 2 para usuario3', 'Create a branding and packaging concept for a line of eco-friendly products. Emphasize sustainable materials and design elements that convey the brands commitment to environmental responsibility', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/qoon2getrstq0hdpk0vq', 3, 'DESIGN'),
('Immersive Vr Art Gallery', 'Tecnologías del O neno do entroido', 'Subtítulo del O neno do entroido', 'An idea of an immersive virtual reality experience showcasing a collection of artworks from various artists. Users can explore the gallery, interact with the art pieces, and even step inside the paintings or sculptures. This project merges technology and art, providing a unique and interactive way for art enthusiasts to experience and appreciate different artistic creations.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/of28wsotzbfzwslkyxog', 3, 'DEVELOPMENT');

-- Publicaciones para usuario4
INSERT INTO posts (title, technologies, subTitle, description, media, user_id, category) VALUES
('Minimalist Home Automation Interface', 'Tecnologías de la publicación 1 para usuario4', 'Subtítulo de la publicación 1 para usuario4', 'Sleek and user-friendly interface for a home automation system, focusing on simplicity and intuitive controls. The goal is to create a visually appealing and accessible experience for users managing smart home devices', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/f18c5g1iehxghsmskehx',4, 'DESIGN'),
('Comprehensive cryptocurrency portfolio', 'Tecnologías de la publicación 2 para usuario4', 'Subtítulo de la publicación 2 para usuario4', 'Comprehensive cryptocurrency portfolio tracker that allows users to manage their digital assets, track market trends, and receive real-time notifications. The platform can support multiple cryptocurrencies and exchanges', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/sb2pfgk9nkkqlbkqtrjf', 4, 'DEVELOPMENT');

-- Publicaciones para usuario5
INSERT INTO posts (title, technologies, subTitle, description, media, user_id, category) VALUES
('Chatas Ibiza', 'Tecnologías de la publicación 1 para usuario5', 'Subtítulo de la publicación 1 para usuario5', 'Unique jewelry brand specializing in earrings and necklaces inspired by the beauty of Ibiza. The website design aims to showcase the artisanal craftsmanship of each piece, providing users with an immersive and delightful shopping experience.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/q9bmdf44kickt4vi6qws', 5, 'DESIGN'),
('Luminous Installation', 'Tecnologías de la publicación 2 para usuario5', 'Subtítulo de la publicación 2 para usuario5', 'We will develop a generative application using complex algorithms to create dreamlike and surreal landscapes in real-time. Users can interact with the application to explore imaginary worlds, inspiring creativity and providing a visually unique and stimulating experience.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/oujghbq4sriehzdwr424', 5, 'DESIGN'),
('Virtual FashionWeek', 'Tecnologías de la página web favorita de Mónica', 'Subtítulo de la página web favorita de Mónica', 'Design a virtual reality experience for a fashion show, allowing users to attend and explore the latest collections from the comfort of their homes. Consider interactive elements and immersive visuals to enhance the overall experience', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/fvraqsm7fyzhihvlt8xl', 5, 'DEVELOPMENT');

INSERT INTO posts (title, technologies, subTitle, description, media, user_id, category) VALUES
('Smart Garden Monitoring System', 'Arduino, Sensors, IoT', 'Automated Plant Care', 'Develop a smart garden monitoring system using Arduino and various sensors to monitor soil moisture, temperature, and light intensity. The system will send alerts to the user\'s smartphone and automatically water the plants when needed.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/h0moahzdn8vhs6jya2kh', 12, 'DEVELOPMENT'),
('Interactive Portfolio Website', 'HTML, CSS, JavaScript, React', 'Showcasing Your Work', 'Create an interactive portfolio website to showcase your projects, skills, and experience. The website will feature a dynamic gallery, contact form, and a blog section to keep visitors updated with your latest work.', 'https://example.com/portfolio-website.jpg', 2, 'DESIGN'),
('AI-Powered Recipe App', 'Python, TensorFlow, Flask', 'Personalized Cooking Experience', 'Build an AI-powered recipe app that suggests recipes based on the ingredients available in your kitchen. The app will use machine learning algorithms to provide personalized recommendations and dietary suggestions.', 'https://example.com/recipe-app.jpg', 3, 'DEVELOPMENT'),
('Virtual Reality Travel Experience', 'Unity, C#, Oculus Rift', 'Immersive Travel Adventures', 'Design a virtual reality travel experience that allows users to explore different parts of the world from the comfort of their home. The project will include 360-degree videos, interactive tours, and educational content about various destinations.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/aafk5i2j2erysnkvgt5p', 14, 'DESIGN'),
('Eco-Friendly Shopping Platform', 'Java, Spring Boot, MySQL', 'Sustainable Shopping', 'Develop an eco-friendly shopping platform that promotes sustainable products and green practices. The platform will feature a marketplace for eco-friendly goods, user reviews, and a carbon footprint calculator.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/pp5rkhbjuimnz3m9p4i9', 16, 'DEVELOPMENT'),
('Artistic Photo Editing App', 'Swift, Core Image, iOS', 'Creative Photo Enhancements', 'Create an artistic photo editing app for iOS that offers a variety of creative filters and effects. Users can apply artistic styles to their photos, such as watercolor, oil painting, and sketch effects.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/yz6imdi2y2wg3kob4hoi', 6, 'DESIGN'),
('Blockchain-Based Voting System', 'Solidity, Ethereum, Web3.js', 'Secure and Transparent Elections', 'Develop a blockchain-based voting system that ensures secure and transparent elections. The system will use smart contracts to record votes immutably and provide real-time election results.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/qktlkca3kejbko81wdva', 7, 'DEVELOPMENT'),
('Responsive E-Commerce Website', 'HTML, CSS, JavaScript, Node.js', 'Seamless Online Shopping', 'Build a responsive e-commerce website that offers a seamless shopping experience across all devices. The website will feature product listings, a shopping cart, and a secure checkout process.', 'https://example.com/ecommerce-website.jpg', 8, 'DESIGN'),
('Fitness Tracking App', 'Kotlin, Firebase, Android', 'Personalized Fitness Plans', 'Create a fitness tracking app for Android that provides personalized workout plans and tracks users\' progress. The app will include features such as exercise tutorials, progress charts, and social sharing options.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/xxayunl47bj86bvcxalo', 9, 'DEVELOPMENT'),
('3D Modeling Tool', 'Blender, Python, OpenGL', 'Creative 3D Design', 'Develop a 3D modeling tool that allows users to create and manipulate 3D objects with ease. The tool will offer various modeling techniques, texture mapping, and rendering options.', 'https://res.cloudinary.com/dnc3btlfa/image/upload/f_auto,q_auto/v1/TheSphere/hokgi2qattc6qvthpr3r', 10, 'DESIGN');


-- Insertar comentarios
INSERT INTO comments (content, user_id, post_id) VALUES
('¡Increíble proyecto! Las Islas Canarias son un paraíso que merece ser mostrado.', 6, 1),
('El diseño del sitio web accesible suena fantástico. ¡Buena suerte!', 1, 2),
('La aplicación de hábitos ecológicos me parece una excelente idea. ¡Sigamos cuidando el planeta!', 7, 3),
('Me encanta la idea de un asistente de salud personal impulsado por IA. ¡Muy innovador!', 4, 4),
('La marca y el empaque de productos sostenibles es un paso importante hacia un futuro más verde.', 2, 5),
('¡Una galería de arte en realidad virtual sería una experiencia impresionante!', 8, 6),
('Una interfaz de automatización del hogar minimalista es justo lo que necesitamos para hacer nuestras vidas más fáciles.', 2, 7),
('Seguir las tendencias del mercado de criptomonedas en tiempo real es esencial. ¡Gran idea!', 4, 8),
('La marca de joyería inspirada en Ibiza es única. ¡Me encanta el concepto!', 1, 9),
('Las instalaciones luminosas siempre añaden un toque mágico a cualquier entorno. ¡Buen trabajo!', 4, 10),
('Una semana de la moda virtual es el futuro. ¡No puedo esperar para ver cómo resulta!', 10, 11);

